// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLThuvien.Models;

#nullable disable

namespace QLThuvien.Migrations.ThuVienDb
{
    [DbContext(typeof(ThuVienDbContext))]
    partial class ThuVienDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLThuvien.Models.BanTheSach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucSachId")
                        .HasColumnType("int")
                        .HasColumnName("DanhMucSach_id");

                    b.Property<string>("MaVach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__BanTheSa__3213E83F3B3E4872");

                    b.HasIndex("DanhMucSachId");

                    b.HasIndex(new[] { "MaVach" }, "UQ__BanTheSa__8BBF4A1C11D752B6")
                        .IsUnique();

                    b.ToTable("BanTheSach", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.BaoCaoVongQuaySach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucSachId")
                        .HasColumnType("int")
                        .HasColumnName("DanhMucSach_id");

                    b.Property<DateTime>("ThoiGianBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ThongKeLuotMuon")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BaoCaoVo__3213E83FD454339F");

                    b.HasIndex("DanhMucSachId");

                    b.ToTable("BaoCaoVongQuaySach", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.BoSungTaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapNhat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DanhMucSachId")
                        .HasColumnType("int")
                        .HasColumnName("DanhMucSach_id");

                    b.Property<string>("DeXuat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("XuLy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__BoSungTa__3213E83FB2FE54A4");

                    b.HasIndex("DanhMucSachId");

                    b.ToTable("BoSungTaiLieu", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.DanhMucSach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NhomSachId")
                        .HasColumnType("int")
                        .HasColumnName("NhomSach_id");

                    b.Property<int>("Slton")
                        .HasColumnType("int")
                        .HasColumnName("SLTon");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ViTriKe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__DanhMucS__3213E83FD6019CF9");

                    b.HasIndex("NhomSachId");

                    b.HasIndex(new[] { "TacGia" }, "IX_Sach_TacGia");

                    b.HasIndex(new[] { "TenSach" }, "IX_Sach_TenSach");

                    b.HasIndex(new[] { "MaSach" }, "UQ__DanhMucS__B235742C011C7345")
                        .IsUnique();

                    b.ToTable("DanhMucSach", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.DatPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GioBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("GioKetThuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PhongId")
                        .HasColumnType("int")
                        .HasColumnName("Phong_id");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__DatPhong__3213E83FAAEB3603");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PhongId", "GioBatDau", "GioKetThuc" }, "IX_DatPhong_Phong");

                    b.ToTable("DatPhong", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.DatTruocSach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucSachId")
                        .HasColumnType("int")
                        .HasColumnName("DanhMucSach_id");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__DatTruoc__3213E83F5D2CF91A");

                    b.HasIndex("DanhMucSachId");

                    b.HasIndex("UserId");

                    b.ToTable("DatTruocSach", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.HanMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxBooks")
                        .HasColumnType("int");

                    b.Property<int>("MaxDays")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxFines")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MaxRenewals")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("PK__HanMuc__3213E83F8306B867");

                    b.HasIndex("RoleId");

                    b.ToTable("HanMuc", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.MuonTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BanTheSachId")
                        .HasColumnType("int")
                        .HasColumnName("BanTheSach_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime");

                    b.Property<int>("SoLanGiaHan")
                        .HasColumnType("int");

                    b.Property<int>("TheId")
                        .HasColumnType("int")
                        .HasColumnName("the_id");

                    b.Property<decimal?>("TienPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__MuonTra__3213E83F0D752CBC");

                    b.HasIndex("BanTheSachId");

                    b.HasIndex(new[] { "TheId" }, "IX_MuonTra_The_Open")
                        .HasFilter("([TrangThai]='open')");

                    b.ToTable("MuonTra", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.NhomSach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__NhomSach__3213E83F7EE02729");

                    b.HasIndex(new[] { "MaNhom" }, "UQ__NhomSach__234F91CC048CCA06")
                        .IsUnique();

                    b.ToTable("NhomSach", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.Phong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("LoaiPhong")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenPhong");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Phong__3213E83F169ACA9C");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Role__3213E83F8B0E788F");

                    b.HasIndex(new[] { "Name" }, "UQ__Role__72E12F1B162A7D2C")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.ThamSoHeThong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__ThamSoHe__3213E83F18B7E309");

                    b.HasIndex(new[] { "Ten" }, "UQ__ThamSoHe__C451FA839DD50A7D")
                        .IsUnique();

                    b.ToTable("ThamSoHeThong", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.The", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HanThe")
                        .HasColumnType("datetime");

                    b.Property<string>("TheCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("The_code");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__The__3213E83FA205BDF9");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TheCode" }, "UQ__The__F4DC115952C80D47")
                        .IsUnique();

                    b.ToTable("The", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83F72144F6C");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E6164424CEEE9")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.ViPhamUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountNoShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("CountTreHan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__ViPhamUs__3213E83FD1117D98");

                    b.HasIndex("UserId");

                    b.ToTable("ViPhamUser", (string)null);
                });

            modelBuilder.Entity("QLThuvien.Models.BanTheSach", b =>
                {
                    b.HasOne("QLThuvien.Models.DanhMucSach", "DanhMucSach")
                        .WithMany("BanTheSaches")
                        .HasForeignKey("DanhMucSachId")
                        .IsRequired()
                        .HasConstraintName("FK__BanTheSac__DanhM__4222D4EF");

                    b.Navigation("DanhMucSach");
                });

            modelBuilder.Entity("QLThuvien.Models.BaoCaoVongQuaySach", b =>
                {
                    b.HasOne("QLThuvien.Models.DanhMucSach", "DanhMucSach")
                        .WithMany("BaoCaoVongQuaySaches")
                        .HasForeignKey("DanhMucSachId")
                        .IsRequired()
                        .HasConstraintName("FK__BaoCaoVon__DanhM__693CA210");

                    b.Navigation("DanhMucSach");
                });

            modelBuilder.Entity("QLThuvien.Models.BoSungTaiLieu", b =>
                {
                    b.HasOne("QLThuvien.Models.DanhMucSach", "DanhMucSach")
                        .WithMany("BoSungTaiLieus")
                        .HasForeignKey("DanhMucSachId")
                        .HasConstraintName("FK__BoSungTai__DanhM__6477ECF3");

                    b.Navigation("DanhMucSach");
                });

            modelBuilder.Entity("QLThuvien.Models.DanhMucSach", b =>
                {
                    b.HasOne("QLThuvien.Models.NhomSach", "NhomSach")
                        .WithMany("DanhMucSaches")
                        .HasForeignKey("NhomSachId")
                        .IsRequired()
                        .HasConstraintName("FK__DanhMucSa__NhomS__3D5E1FD2");

                    b.Navigation("NhomSach");
                });

            modelBuilder.Entity("QLThuvien.Models.DatPhong", b =>
                {
                    b.HasOne("QLThuvien.Models.Phong", "Phong")
                        .WithMany("DatPhongs")
                        .HasForeignKey("PhongId")
                        .IsRequired()
                        .HasConstraintName("FK__DatPhong__Phong___60A75C0F");

                    b.HasOne("QLThuvien.Models.User", "User")
                        .WithMany("DatPhongs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__DatPhong__user_i__619B8048");

                    b.Navigation("Phong");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLThuvien.Models.DatTruocSach", b =>
                {
                    b.HasOne("QLThuvien.Models.DanhMucSach", "DanhMucSach")
                        .WithMany("DatTruocSaches")
                        .HasForeignKey("DanhMucSachId")
                        .IsRequired()
                        .HasConstraintName("FK__DatTruocS__DanhM__74AE54BC");

                    b.HasOne("QLThuvien.Models.User", "User")
                        .WithMany("DatTruocSaches")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__DatTruocS__user___75A278F5");

                    b.Navigation("DanhMucSach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLThuvien.Models.HanMuc", b =>
                {
                    b.HasOne("QLThuvien.Models.Role", "Role")
                        .WithMany("HanMucs")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__HanMuc__role_id__6FE99F9F");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QLThuvien.Models.MuonTra", b =>
                {
                    b.HasOne("QLThuvien.Models.BanTheSach", "BanTheSach")
                        .WithMany("MuonTras")
                        .HasForeignKey("BanTheSachId")
                        .IsRequired()
                        .HasConstraintName("FK__MuonTra__BanTheS__5812160E");

                    b.HasOne("QLThuvien.Models.The", "The")
                        .WithMany("MuonTras")
                        .HasForeignKey("TheId")
                        .IsRequired()
                        .HasConstraintName("FK__MuonTra__the_id__571DF1D5");

                    b.Navigation("BanTheSach");

                    b.Navigation("The");
                });

            modelBuilder.Entity("QLThuvien.Models.The", b =>
                {
                    b.HasOne("QLThuvien.Models.User", "User")
                        .WithMany("Thes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__The__user_id__4E88ABD4");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLThuvien.Models.User", b =>
                {
                    b.HasOne("QLThuvien.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__User__role_id__49C3F6B7");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QLThuvien.Models.ViPhamUser", b =>
                {
                    b.HasOne("QLThuvien.Models.User", "User")
                        .WithMany("ViPhamUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ViPhamUse__user___7B5B524B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLThuvien.Models.BanTheSach", b =>
                {
                    b.Navigation("MuonTras");
                });

            modelBuilder.Entity("QLThuvien.Models.DanhMucSach", b =>
                {
                    b.Navigation("BanTheSaches");

                    b.Navigation("BaoCaoVongQuaySaches");

                    b.Navigation("BoSungTaiLieus");

                    b.Navigation("DatTruocSaches");
                });

            modelBuilder.Entity("QLThuvien.Models.NhomSach", b =>
                {
                    b.Navigation("DanhMucSaches");
                });

            modelBuilder.Entity("QLThuvien.Models.Phong", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("QLThuvien.Models.Role", b =>
                {
                    b.Navigation("HanMucs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("QLThuvien.Models.The", b =>
                {
                    b.Navigation("MuonTras");
                });

            modelBuilder.Entity("QLThuvien.Models.User", b =>
                {
                    b.Navigation("DatPhongs");

                    b.Navigation("DatTruocSaches");

                    b.Navigation("Thes");

                    b.Navigation("ViPhamUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
